# # This file deploys Alloy as a DaemonSet on every node
# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: alloy
#   namespace: telemetry-system
# spec:
#   selector:
#     matchLabels:
#       app: alloy
#   template:
#     metadata:
#       labels:
#         app: alloy
#     spec:
#       containers:
#       - name: alloy
#         image: grafana/alloy:latest
#         args: ["run", "--stability.level=public-preview", "--server.http.listen-addr=0.0.0.0:12345", "/etc/alloy/config.alloy"]
#         ports:
#         - containerPort: 4317
#         - containerPort: 4318
#         - containerPort: 12345
#         volumeMounts:
#         - name: alloy-config
#           mountPath: /etc/alloy/config.alloy
#           subPath: config.alloy
#         - name: varlog
#           mountPath: /var/log
#           readOnly: true
#         - name: varlibdockercontainers
#           mountPath: /var/lib/docker/containers
#           readOnly: true
#       volumes:
#       - name: alloy-config
#         configMap:
#           name: alloy-config
#       - name: varlog
#         hostPath:
#           path: /var/log
#       - name: varlibdockercontainers
#         hostPath:
#           path: /var/lib/docker/containers
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: alloy
#   namespace: telemetry-system
# spec:
#   selector:
#     app: alloy
#   ports:
#   - name: otlp-grpc
#     port: 4317
#     targetPort: 4317
#   - name: otlp-http
#     port: 4318
#     targetPort: 4318
#   - name: ui
#     port: 12345
#     targetPort: 12345
#   type: ClusterIP
