# This file deploys your application on the application node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: telemetry-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
        node-type: application
    spec:
      nodeSelector:
        role: application
      containers:
      - name: node-app
        image: testnode-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy:4317"  # Use the service name instead of NODE_IP
        # - name: NODE_IP
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: telemetry-system
spec:
  selector:
    app: node-app
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
