# This file deploys your application on the application node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: telemetry-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
        node-type: application
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        # Add these annotations for Loki log collection
        loki.grafana.com/scrape: "true"
        loki.grafana.com/format: "json"
    spec:
      nodeSelector:
        role: application
      volumes:
      - name: alloy-config
        configMap:
          name: alloy-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibcontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: proc
        hostPath:
          path: /proc
      containers:
      - name: node-app
        image: testnode-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://localhost:4318"
        - name: NODE_OPTIONS
          value: "--dns-result-order=ipv4first"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://localhost:4318/v1/traces"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: "http://localhost:4318/v1/metrics"
        - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
          value: "http://localhost:4318/v1/logs"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/json"
        # This ensures logs are accessible to the Alloy sidecar
        - name: OTEL_SDK_DISABLED
          value: "false"
        # - name: NODE_IP
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.hostIP
        # No volume mounts needed for standard stdout/stderr logging
      # Add alloy collector as a sidecar
      - name: alloy-sidecar
        image: grafana/alloy:latest
        args: ["run", "--stability.level=public-preview", "--server.http.listen-addr=0.0.0.0:12345", "/etc/alloy/config.alloy"]
        ports:
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 12345
        # Give Alloy access to container logs
        volumeMounts:
        - name: alloy-config
          mountPath: /etc/alloy/config.alloy
          subPath: config.alloy
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibcontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: proc
          mountPath: /proc
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: telemetry-system
spec:
  selector:
    app: node-app
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
